# configs/sweeps/tf_struct_sweep.yaml

program: src.launch.train     # 对应 python -m src.launch.train
name: CheapCTSNet_sweep
method: bayes                # 也可以先改成 random，后面解释
metric:
  name: test/test/last_sweep/pr_auc            # 对应你 WandB summary 里写入的 key
  goal: maximize

parameters:
  # model.d_model:
  #   values: [128, 256]
  # model.n_layers:
  #   values: [2, 4]
  # model.n_heads:
  #   values: [4, 8]
  # model.dim_ff:
  #   values: [512, 1024]
  model.dropout:
    values: [0.1, 0.0]
  run.num_epochs:
    values: [50, 60, 80, 100]
  run.batch_size:
    values: [32, 64, 128, 256]
  train.lr:
    values: [0.0001, 0.0005, 0.001, 0.005]

command:
  - ${env}
  - ${interpreter}
  - -m
  - src.launch.train
  - experiment=CheapCTSNet
  - logging.wandb.enabled=true
  - logging.wandb.project=CheapCTSNet
  - logging.wandb.group=CheapCTSNet_sweep
  - ${args_no_hyphens}   # ⭐ 关键修改
